---

 - name: install mysql
   yum: name=mysql-server update_cache=yes state=present
   when: ansible_distribution == "Amazon"

 - name: creating a mysql user
   mysql_user: name=ishan password=ishan priv='*.*:ALL,GRANT' state=present
   when: ansible_distribution == "Amazon"


 - name: creating a database
   mysql_db: name=employeedb state=present
   when: ansible_distribution == "Amazon"

 - name: restarting a service
   service: name=mysqld state=restarted
   when: ansible_distribution == "Amazon"
 
