-
-

 - name: install mysql
   yum: name=mysql-server update_cache=yes state=present
   when: ansible_distribution == "Amazon"

 - name: restarting a service
   service: name=mysqld state=restarted
   when: ansible_distribution == "Amazon"
 
