---

 - name : install pip
   apt: name=python-pip state=present update_cache=yes
   when: ansible_distribution == "Ubuntu"

 - name: install mysql
   apt: name=python-mysqldb update_cache=yes state=present force=yes
   when: ansible_distribution == "Ubuntu"

 - name: creating a mysql user
   mysql_user: name=ishan password=ishan priv='*.*:ALL,GRANT' state=present
   when: ansible_distribution == "Ubuntu"


 - name: creating a database
   mysql_db: name=employeedb state=present
   when: ansible_distribution == "Ubuntu"

 - name: restarting a service
   service: name=mysql state=restarted
   when: ansible_distribution == "Ubuntu"

